#!/bin/sh

if [ x$1 == x ]; then
    echo "usage: vimrun FILE"
    exit 1
fi

if [[ $1 =~ /* ]]; then
    FILE_PATH=$1 # Absolute path
else
    FILE_PATH=`pwd`/$1 # Relative path
fi

FILE_NAME=`basename $FILE_PATH`
FILE_EXT=${FILE_NAME##*.}

run() {
    echo \$ $*
    $*
}

case "$FILE_EXT" in
    "py")
        if [[ $FILE_NAME =~ test_* ]]; then
            if [[ -d __ ]]; then
                PYTEST=__/bin/py.test
            else
                PYTEST=py.test
            fi
            run $PYTEST $FILE_PATH
        else
            run python $FILE_PATH
        fi
        ;;
    "hs")
        run runhaskell $FILE_PATH
        ;;
    *)
        if [ -x $FILE_PATH ]; then
            run $FILE_PATH
        else
            echo "Don't know how to run $FILE_PATH"
        fi
esac 
